### PR TITLE
Adding copyright notice

### LINKED ISSUE #2: Add a license to the website
In order for people to create derivatives of the website, they need permission. The best way to do this is through a license. Existing copyright holders will have to agree on a license and relicense this site.

### PR DESCRIPTION
**Pull request by nicolasmaia**
By accepting this PR, the person in charge confirms that they have the explicit permission of all relevant parties to make this change lawfully. Should fix #2

### CODE REVIEW

**Review by victoredwardocallaghan — APPROVED** [review]
Yea fair enough, here is my +1.

**Comment by Jookia** [comment]
What needs to be done to get this merged?

**Comment by zamaudio** [comment]
I give it +1 too

**Comment by zamaudio** [comment]
Ok, +1

**Review by zamaudio — APPROVED** [review]
Ok +1

**Pull request closed without merging**
